### ISSUE TITLE
How to connect to Rpi

### ISSUE THREAD

**Issue by DankInstitute** [mhar9000/OctoPrint-Arduino-NeoPixel#2]
Hello! I am very excited about this plugin and hope it gets officially registered soon! 

One issue i have is that nowhere in the readme do you describe how to connect the rPi to the arduino?

Is it simply connected through one of the USB ports or do I need to connect to the GPIO pins? 

I was unable to find any information where it's receiving the data in the INO and beyond that, I am stumped. 

Thank you in advance for taking the time to make this great plugin!

**Comment by MattElek** [comment]
You just have to connect it over USB, sorry it wasn't clear. I'll update the readme, and I actually forgot to register it because it's been a while since I've worked on this, so thank you for the reminder! Let me know if you have any other questions.
